[tool.robotidy]
transform = [
  "AlignTemplatedTestCases",
  "AddMissingEnd",
  "NormalizeSeparators",
  "DiscardEmptySections",
  "MergeAndOrderSections",
  "RemoveEmptySettings",
  "NormalizeAssignments",
  "OrderSettings",
  "OrderSettingsSection",
  "OrderTags",
  "AlignSettingsSection:up_to_column=3",
  "AlignVariablesSection",
  "NormalizeNewLines:section_lines=2",
  "NormalizeSectionHeaderName",
  "NormalizeSettingName",
  "ReplaceRunKeywordIf",
  "DiscardEmptySections:allow_only_comments=True",
  "SplitTooLongLine:line_length=150",
  "SmartSortKeywords",
  "RenameTestCases:capitalize_each_word=True",
  "ReplaceBreakContinue",
  "ReplaceReturns",
]